image: node:16.16.0
pages:
  stage: deploy
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    